version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    configs:
      - source: nginx_conf_drf
        target: /etc/nginx/nginx.conf
    ports:
      - mode: host
        protocol: tcp
        target: 80
        published: 80
    networks:
      - gis_network
    volumes:
      - gis_static:/data/static/
      - gis_media:/data/media/
      - gis_log:/var/log/nginx/

  django:
    image: gis_drf_2:1.0
    networks:
      - gis_network
    volumes:
      - gis_static:/home/gis_drf_2/staticfiles/
      - gis_media:/home/gis_drf_2/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER # django
      - MARIADB_PASSWORD # password1234
      - MARIADB_ROOT_PASSWORD # password1234
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD


networks:
  gis_network:

configs:
  nginx_conf_drf:
    external: true

volumes:
  gis_static:
  gis_media:
  gis_mariadb:
  gis_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  NGINX_AUTH:
    external: true
